#!/bin/zsh

if [[ $1 == "--gitlab" ]]; then
    git clone git@gitlab.com:/$2/$3
elif [[ $1 == "--metro" ]]; then
    git clone git@git.metrosystems.net:/$2/$3
else
    git clone git@github.com:/$1/$2
fi


