#!/bin/zsh

declare -a ignore=("fonts" "shell" "plugged" "readme.md")

function Ignore() {
    for e in "${ignore[@]}"; do
        if [[ $e == $1 ]]; then
            echo "yes"
            return
        fi
    done
    echo "no"
}

function Link() {
    if [[ -d $1 ]]; then
        echo "Rec: --> $1"
        mkdir -p $1
        for file in $(/usr/bin/ls $2); do
            if [[ $(Ignore $file) == "no" ]]; then
                Link $1/$file $2/$file
            fi
        done
    else
        echo "Inst: $1 --> $2"
        [[ -e $1 ]] || ln -s $2 $1
    fi
}

for file in $(/usr/bin/ls $HOME/Documents/dotfiles); do
    if [[ $(Ignore $file) == "no" ]]; then
        Link $HOME/.$file $HOME/Documents/dotfiles/$file
    fi
done

. ~/.zshrc
echo "Done"
