#!/bin/zsh

# A specific list of packages is specified for both ubuntu and arch linux.
# This script goes through each of these, checks if they exist in the
# official repositories, if they exist on the local computer and installs
# accordingly.

sudo pacman -Suy

declare -a packages=(
                     "xorg-bdftopcf"
                     "xorg-iceauth"
                     "xorg-luit"
                     "xorg-mkfontscale"
                     "xorg-sessreg"
                     "xorg-setxkbmap"
                     "xorg-smproxy"
                     "xorg-x11perf"
                     "xorg-xauth"
                     "xorg-xbacklight"
                     "xorg-xcmsdb"
                     "xorg-xcursorgen"
                     "xorg-xdpyinfo"
                     "xorg-xdriinfo"
                     "xorg-xev"
                     "xorg-xgamma"
                     "xorg-xhost"
                     "xorg-xinput"
                     "xorg-xkbcomp"
                     "xorg-xkbevd"
                     "xorg-xkbutils"
                     "xorg-xkill"
                     "xorg-xlsatoms"
                     "xorg-xlsclients"
                     "xorg-xmodmap"
                     "xorg-xpr"
                     "xorg-xprop"
                     "xorg-xrandr"
                     "xorg-xrdb"
                     "xorg-xrefresh"
                     "xorg-xset"
                     "xorg-xsetroot"
                     "xorg-xvinfo"
                     "xorg-xwd"
                     "xorg-xwininfo"
                     "xorg-xwud"
                     "xorg-server"
                     "xorg-xinit"
                     "xorg-fonts-100dpi"
                     "xorg-fonts-75dpi"
                     "xorg-fonts-alias"
                     "xorg-fonts-cyrillic"
                     "xorg-fonts-encodings"
                     "xorg-fonts-misc"
                     "xorg-fonts-type1"
                     "htop"
                     "git"
                     "ghc"
                     "ruby"
                     "go"
                     "scala"
                     "exa"
                     "xscreensaver"
                     "jdk8-openjdk"
                     "cabal-install"
                     "texlive-core"
                     "fzf"
                     "net-tools"
                     "dzen2"
                     "pulseaudio"
                     "pulseaudio-alsa"
                     "pavucontrol"
                     "alsa-utils"
                     "mplayer"
                     "wget"
                     "rxvt-unicode"
                     "rxvt-unicode-terminfo"
                     "xmonad"
                     "xmonad-contrib"
                     "ttf-indic-otf"
                     "ttf-dejavu"
                     "sdl2_ttf"
                     "ttf-liberation"
                     "ttf-droid"
                     "firefox"
                     "thunderbird"
                     "unzip"
                     "tmux"
                     "openssh"
                     "scrot"
                     "feh"
                     "vim"
                     "neovim"
                     "graphviz"
                     "the_silver_searcher"
                     "pwgen"
                     "fd"
                     "cmake"
                     "python2"
                     "python-virtualenv"
                     "python-requests"
                     "python-regex"
                     "python-dateutil"
                     "pyalpm"
                     "python-feedparser"
                     "pydf"
                     "python-pip"
                     "python2-pip"
                     "expac"
                     "redshift"
                     "gimp"
                     "ristretto"
                     "scrot"
                     "pass"
                     "zsh"
                     "jq"
                     "meson"
                     "gtest"
                     "gmock"
                     "curl"
                     "emacs"
                     "screenfetch"
                     "cronie"
                     "zathura"
                     "zathura-pdf-poppler")

all_packages=""
for package in "${packages[@]}"
do
    pacman -Qi $package > /dev/null
    if [[ $? == "1" ]]; then
        all_packages="$all_packages $package"
    fi
done

if [[ $all_packages != "" ]]; then
    sudo pacman -S $(echo "$all_packages" | xargs)
fi

# Neovim
# install with python support
sudo pip install neovim
if [[ ! -f "$HOME/.config/nvim/init.vim" ]]; then
    mkdir -p $HOME/.config/nvim
    nvim=$HOME/.config/nvim/init.vim
    touch $nvim
    echo "set runtimepath^=~/.vim runtimepath+=~/.vim/after" > $nvim
    echo "let &packpath = &runtimepath" >> $nvim
    echo "source ~/.vimrc" >> $nvim
fi

# trans
which trans > /dev/null 2>&1
if [[ $? == "1" ]]; then
    wget git.io/trans
    chmod +x ./trans
    mv trans $HOME/.bin
fi

# lein
which lein > /dev/null 2>&1
if [[ $? == "1" ]]; then
    wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod +x ./lein
    mv lein $HOME/.bin
fi


# stack and pandoc
which stack > /dev/null 2>&1
if [[ $? == "1" ]]; then
    curl -sSL https://get.haskellstack.org/ | sh
fi

PrintSeparator "Setting up haskell"
stack update

