#!/bin/zsh

# A specific list of packages is specified for both ubuntu and arch linux.
# This script goes through each of these, checks if they exist in the
# official repositories, if they exist on the local computer and installs
# accordingly.

sudo pacman -Suy

declare -a packages=("htop"
                     "git"
                     "ghc"
                     "ruby"
                     "go"
                     "scala"
                     "exa"
                     "xscreensaver"
                     "jdk8-openjdk"
                     "cabal-install"
                     "texlive-core"
                     "fzf"
                     "net-tools"
                     "dzen2"
                     "pulseaudio"
                     "pulseaudio-alsa"
                     "pavucontrol"
                     "alsa-utils"
                     "mplayer"
                     "wget"
                     "rxvt-unicode"
                     "rxvt-unicode-terminfo"
                     "xmonad"
                     "xmonad-contrib"
                     "xorg-server"
                     "xorg-apps"
                     "xorg-init"
                     "xorg-fonts-100dpi"
                     "xorg-fonts-75dpi"
                     "xorg-fonts-alias"
                     "xorg-fonts-cyrillic"
                     "xorg-fonts-encodings"
                     "xorg-fonts-misc"
                     "xorg-fonts-type1"
                     "firefox"
                     "unzip"
                     "tmux"
                     "openssh"
                     "scrot"
                     "feh"
                     "vim"
                     "neovim"
                     "graphviz"
                     "the_silver_searcher"
                     "pwgen"
                     "fd"
                     "cmake"
                     "python2"
                     "python-virtualenv"
                     "python-requests"
                     "python-regex"
                     "python-dateutil"
                     "pyalpm"
                     "python-feedparser"
                     "pydf"
                     "python-pip"
                     "python2-pip"
                     "expac"
                     "redshift"
                     "gimp"
                     "ristretto"
                     "scrot"
                     "pass"
                     "zsh"
                     "curl"
                     "emacs"
                     "screenfetch"
                     "cronie"
                     "zathura"
                     "zathura-pdf-poppler")

for package in "${packages[@]}"
do
    echo -n  "$package..."
    pacman -Ss ^$package$ > /dev/null 2>&1

    if [[ $? == "1" ]]; then
        echo "Package $package does not exist" && exit
    fi
    echo "available"
done

sudo pacman -S $packages

# Neovim
# install with python support
sudo pip install neovim
if [[ ! -f "$HOME/.config/nvim/init.vim" ]]; then
    mkdir -p $HOME/.config/nvim
    nvim=$HOME/.config/nvim/init.vim
    touch $nvim
    echo "set runtimepath^=~/.vim runtimepath+=~/.vim/after" > $nvim
    echo "let &packpath = &runtimepath" >> $nvim
    echo "source ~/.vimrc" >> $nvim
fi

# trans
which trans > /dev/null 2>&1
if [[ $? == "1" ]]; then
    wget git.io/trans
    chmod +x ./trans
    mv trans $HOME/.bin
fi

# lein
which lein > /dev/null 2>&1
if [[ $? == "1" ]]; then
    wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod +x ./lein
    mv lein $HOME/.bin
fi


# stack and pandoc
which stack > /dev/null 2>&1
if [[ $? == "1" ]]; then
    curl -sSL https://get.haskellstack.org/ | sh
fi

PrintSeparator "Setting up haskell"
stack update

