#!/bin/zsh

if [[ $(cat /etc/hostname) == "keysersoze" ]]; then
    device=nvme0n1p2
else
    device=luks_root
fi

echo $(/usr/bin/df -h | grep $device | tr -s ' ' | cut -d' ' -f5) > "$HOME/Data/log/store/disk.txt"
