#!/bin/zsh

echo "Available screens:\n"
while read -r line; do
    echo $line
done <<< "$(xrandr | grep connected | cut -d' ' -f1,2)"

echo "\nExamples:"
echo "xrandr --output SCREEN --auto"
echo "xrandr --output SCREEN --off"
