#!/bin/zsh

prefix=${1:0:${#1}-1}
suffix=${1:${#1}-1:${#1}}

if [[ $suffix == "s" ]]; then
    echo $prefix
elif [[ $suffix == "m" ]]; then
    echo $((prefix * 60))
elif [[ $suffix == "h" ]]; then
    echo $((prefix * 60 * 60))
else
    "Unknown format: $1"
    exit 1
fi
