#!/bin/zsh

# ############################################################################
# Setup

fifofile=/home/lsund/.mplayer/fifo

if [[ ! -e $fifofile ]] ; then
    echo "Creating fifo..."
    mkfifo $fifofile
    echo "input=file=$fifofile" >> "/home/lsund/.mplayer/config"
fi

session_file="$HOME/.${USER}_session"
[[ ! -e $session_file ]] && echo "0\n0\n0\npaused\n0" > $session_file

# ############################################################################
# Script

music_path=$HOME/Media/audio/music

init_ts=$(cat $session_file | head -1)
pause_ts=$(cat $session_file | head -2 | tail -1)
continue_ts=$(cat $session_file | head -3 | tail -1)
state=$(cat $session_file | head -4 | tail -1)
seconds=$(cat $session_file | tail -5 | tail -1)

rand_file="$music_path/$(/usr/bin/ls -1 $music_path | shuf | head -1)"

[[ $rand_file == "" ]] && echo "No music files" && exit 1

is_mplayer_active=$(pgrep -u lsund mplayer)

if [[ $1 == "reset" ]]; then
    echo "Resetting session. Current time: $(show-time 0)."
    echo "0\n0\n0\npaused\n0" > $session_file
    if [[ $is_mplayer_active ]]; then
        echo "quit" > $fifofile
    fi
    exit 0
elif [[ $1 == "time" && $state == "started" ]]; then
    current_ts=$(date '+%s')
    current_seconds=$((seconds + $current_ts - $pause_ts))
    echo "Current time: $(show-time "$current_seconds")"
elif [[ $1 == "time" && $state == "paused" ]]; then
    echo "Current time: $(show-time "$seconds")"
elif [[ $# == 0 || $1 == "toggle" ]]; then
    files=$(/usr/bin/ls -1 $music_path)
    play_file=$rand_file
    for file in $(echo $files | xargs); do
        if [[ $file == "$1.mp3" ]]; then
            play_file=$music_path/$file
        fi
    done
    if [[ $state == "paused" ]]; then
        continue_ts=$(date '+%s')
        if [[ $seconds == "0" ]]; then
            echo "$continue_ts\n0\n$continue_ts\nstarted\n0" > $session_file
            echo "Starting session. Current time: $(show-time $seconds)."
        else
            echo "$init_ts\n$pause_ts\n$continue_ts\nstarted\n$seconds" > $session_file
            echo "Continuing session. Current time: $(show-time $seconds)."
        fi
        if [[ $is_mplayer_active ]]; then
            # Resume the active instance
            echo "pause" > $fifofile
        else
            echo "Starting $play_file"
            mplayer -quiet -slave $play_file > /dev/null &
        fi
    else
        pause_ts=$(date '+%s')
        new_seconds=$((seconds + pause_ts - continue_ts))
        echo "$init_ts\n$pause_ts\n$continue_ts\npaused\n$new_seconds"  > $session_file
        echo "\nPausing session. Current time: $(show-time $new_seconds)."
        # Pause the active instance
        echo "pause" > $fifofile
    fi
fi

