#!/bin/zsh

# ############################################################################
# Setup

fifofile=/home/lsund/.mplayer/fifo

if [[ ! -e $fifofile ]] ; then
    echo "Creating fifo..."
    mkfifo $fifofile
    echo "input=file=$fifofile" >> "/home/lsund/.mplayer/config"
fi

session_file="$HOME/.${USER}_session"

music_path=$HOME/Media/audio/music

init_ts=$(cat $session_file | head -1)
pause_ts=$(cat $session_file | head -2 | tail -1)
continue_ts=$(cat $session_file | head -3 | tail -1)
state=$(cat $session_file | head -4 | tail -1)
seconds=$(cat $session_file | tail -5 | tail -1)

rand_file="$music_path/$(/usr/bin/ls -1 $music_path | shuf | head -1)"

[[ $rand_file == "" ]] && echo "No music files" && exit 1

is_mplayer_active=$(pgrep -u lsund mplayer)

# ############################################################################
# Helpers

function write_state() {
    echo "$1\n$2\n$3\n$4\n$5" > $session_file
}

function calculate_seconds() {
    seconds=$1
    current_ts=$2
    init_ts=$3
    echo $((seconds + $current_ts - $init_ts))
}

function log_time() {
    echo "Current time: $(show-time "$1")"
}

function toggle_mplayer() {
    echo "pause" > $fifofile
}

# ############################################################################
# Script

[[ ! -e $session_file ]] && write_state 0 0 0 paused 0

if [[ $1 == "reset" ]]; then
    echo "Resetting session. Current time: $(show-time 0)."
    write_state 0 0 0 paused 0
    if [[ $is_mplayer_active ]]; then
        echo "quit" > $fifofile
    fi
    exit 0
elif [[ $1 == "time" && $state == "started" ]]; then
    log_time $(calculate_seconds $seconds $(date '+%s') $continue_ts)
elif [[ $1 == "time" && $state == "paused" ]]; then
    log_time $seconds
elif [[ $# == 0 || $1 == "toggle" ]]; then
    files=$(/usr/bin/ls -1 $music_path)
    play_file=$rand_file
    for file in $(echo $files | xargs); do
        if [[ $file == "$1.mp3" ]]; then
            play_file=$music_path/$file
        fi
    done
    if [[ $state == "paused" ]]; then
        continue_ts=$(date '+%s')
        if [[ $seconds == "0" ]]; then
            write_state $continue_ts 0 $continue_ts started 0
            log_time 0
            echo "Starting session"
        else
            write_state $init_ts $pause_ts $continue_ts started $seconds
            log_time $seconds
            echo "Continuing session"
        fi
        if [[ $is_mplayer_active ]]; then
            toggle_mplayer
        else
            echo "Playing file $play_file"
            mplayer -quiet -slave $play_file > /dev/null &
        fi
    else
        pause_ts=$(date '+%s')
        seconds=$(calculate_seconds $seconds $pause_ts $continue_ts)
        write_state $init_ts $pause_ts $continue_ts paused $seconds
        log_time $seconds
        toggle_mplayer
        echo "Pausing session"
    fi
fi

