#!/bin/zsh
num=$1
min=0
hour=0
day=0
if [[ $((num>59)) ]]; then
    ((sec=num%60))
    ((num=num/60))
    if [[ $((num>59)) ]]; then
        ((min=num%60))
        ((num=num/60))
        if [[ $((num>23)) ]]; then
            ((hour=num%24))
            ((day=num/24))
        else
            ((hour=num))
        fi
    else
        ((min=num))
    fi
else
    ((sec=num))
fi

if [[ $2 == d ]]; then
    echo "$day"d
elif [[ $2 == h ]]; then
    echo "$hour"h
elif [[ $2 == hm ]]; then
    echo "$hour"h "$min"m
else
    echo "$day"d "$hour"h "$min"m "$sec"s
fi
