#!/bin/bash

if [[ $HOSTNAME == "Ludvigs-MBP" ]]; then
  tput bel
  sleep 0.2
  tput bel
  sleep 0.2
  tput bel
  exit 0
fi

audiopath=$HOME/Media/audio/sounds/

if [[ $# == 2 ]]; then
    countdown $2
fi

if [[ $1 == "beep" ]]; then
    file=beep.mp3
elif [[ $1 == "siren" ]]; then
    file=siren.wav
elif [[ $1 == "bell" ]]; then
    file=bell.mp3
elif [[ $1 == "tone" ]]; then
    file=tone.wav
else
    file=beep.mp3
fi

mplayer $audiopath/$file -endpos 00:00:04 &>/dev/null
