#!/bin/zsh

service=$1

if [[ $2 == "personal" ]]; then
    basedir="$HOME/Documents/git/$1"
else
    basedir="$HOME/Documents/work/metro/git/$1"
fi

if [[ -d $basedir ]]; then

    tmux setw remain-on-exit on

    tmux new-window -c $basedir -n $service

    tmux setw remain-on-exit on

    tmux new-window $basedir -n $service

    tmux setw remain-on-exit on

    tmux split-window -v -c $basedir

    tmux setw remain-on-exit on

    tmux resize-pane -D 30

    tmux split-window -h -c $basedir

    tmux setw remain-on-exit on

    tmux split-window -v -c $basedir

    tmux setw remain-on-exit on

    tmux select-pane -L

    tmux setw remain-on-exit on

    tmux split-window -v -c $basedir

    tmux setw remain-on-exit on
else
    echo "$basedir does not exist"
fi
