#!/bin/zsh

# Replaces all spaces in all filenames in the current directory by underscores

for file in "$@" ; do
    if [[ ! -e $file ]]; then
        echo "$file: No such file or directory" && exit 1
    fi
    newname="$(echo $file | sed 's/ /_/g')"
    mv $file $newname
done

