#!/bin/zsh

# Aliases
alias pwd="$SCRIPTS/pwd"
alias gco='git-fuzzy-checkout'
alias watch-file='watch -n 1 -d cat'
alias ports="sudo lsof -Pnl +M -i4"
alias duh="du -h -d 1"
alias n='nnn'
alias df='pydf'
alias vim='fuzzy-vim'
alias ls='ls -lrth --color=auto'
alias ll='ls -larth --color=auto'
alias lsf='ls-full'
alias grep='grep --color'
alias beep='mplayer /home/lsund/Media/audio/sounds/beep.mp3 1>& /dev/null'
alias siren='mplayer /home/lsund/Media/audio/sounds/siren.wav 1>& /dev/null'
alias untargz='tar -xvzf'
alias gpb='git-push-origin-branch'
alias gsb='git-sync-base'
alias un7z='7z e'
alias csvdiff='git diff --color-words="[^[:space:],]+"'
alias keys='setxkbmap dvorak -option compose:caps'
alias shutdown='sudo shutdown now -P'
alias restart='sudo shutdown now -r'
alias tmux='tmux -2'
alias zath='zathura'
alias network-scan='sudo iwlist wlp58s0 scan | grep ESSID'
alias my-ip="curl -s checkip.dyndns.org | \
    sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"
alias combine-pdf='gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite \
    -sOutputFile=$3 $1 $2'
alias redshift='redshift -l 51.2:6.7 -t 5500:3400 -g 0.8 -m randr &'
alias deploy-clj-snapshot='release-snapshot-clj --push && git push heroku master && bump-clj --push'


# cd override
function cd() {
    builtin cd "$@" && ls --color=auto -lrth;
}

# Fuzzy CD. Start an interactive search under directory.
function fcd () {

    fuzzy_prog=fzf

    if [[ $# == 0 || $# == 1 ]]; then

        if [[ $# == 0 ]]; then
            file=$(/usr/bin/ls -p | grep '/' | $fuzzy_prog)
        elif [[ $# == 1 && -e $1 ]]; then
            file=$1
        fi

        echo $file

        if [[ -d $file ]]; then

            search_path="."
            dir=$file
            while [[ -d $search_path/$dir ]]; do
                search_path=$search_path/$dir
                dir=$(/usr/bin/ls -p $search_path | grep '/' | $fuzzy_prog)
                [[ $dir == "" ]] && break
            done
        fi

        if [[ -d $search_path ]]; then
            temp_file=$(mktemp)
            echo "#!/bin/zsh\ncd $search_path" > $temp_file
            source $temp_file
            /usr/bin/rm $temp_file
        fi

    fi
}


