#!/bin/zsh

# ############################################################################
# Util

alias ls='exa -lu --time-style long-iso --color always'
alias la='exa -lau --time-style long-iso --color always'
alias grep='grep --color'
alias vim='nvim'
alias duh="sudo du -h -d 1 2> /dev/null"
alias pingg='ping -c 3 google.com'
alias ghci='stack ghci'
alias agl='ag -l'

if [[ $HOST == "N52930" ]]; then
else
  alias cat='bat --theme zenburn'
fi

alias pwd="$SCRIPTS/pwd"

function cd() {
    builtin cd $1 && ls
}

## APIS

alias td='trans en: :de'

alias te='trans de:'

alias weather='curl wttr.in'

alias public-ip='curl https://ipinfo.io/ip'

alias beep='echo -ne "\\007"'
alias bell='echo -ne "\\007"'

# ############################################################################
# Git

alias gdl='git diff --name-status';

alias gdc='git show --decorate'

alias cdgr='source $DOTFILES/shell/cd-git-root'

alias glogc='git log --graph --simplify-by-decoration --oneline --topo-order --branches'

alias gsst='git status -s'

alias squash='git reset --soft HEAD~2 && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"'

alias csvdiff='git diff --color-words="[^[:space:],]+"'

alias git-delete-all-merged-branches='git branch --merged | grep -v "\*" | grep -v master | grep -v main | xargs -n 1 git branch -d'

function ggg() {
    gaa
    gss
    tag=$(git rev-parse --abbrev-ref HEAD | cut -d'-' -f1)
    issue=$(git rev-parse --abbrev-ref HEAD | cut -d'-' -f1-2)
    if [[ $# == 1 ]]; then
        gcmsg "$issue: $1"
    else
        vared -p "> " -c msg_12341234
        echo "Commit message: $msg_12341234"
        gcmsg "$msg_12341234"
    fi
    msg_12341234=""
}
