
set -g base-index 1
set -g history-limit 10000
set -g default-terminal "screen-256color"

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

unbind w
bind w kill-pane

bind-key -n M-H swap-window -t -1 
bind-key -n M-L swap-window -t +1 

unbind c
bind-key e command-prompt -p "window name:" "new-window; rename-window '%%'"

# Use Alt-arrow keys without prefix key to switch panes
bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R
bind-key -n M-k select-pane -U
bind-key -n M-j select-pane -D

bind-key h resize-pane -L 5
bind-key l resize-pane -R 5
bind-key k resize-pane -U 5
bind-key j resize-pane -D 5

bind-key -n M-J swap-pane -U
bind-key -n M-K swap-pane -D

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

bind r source-file ~/.tmux.conf

set -sg escape-time 0

set -g status-bg black
set -g status-fg white
set -g window-status-current-bg white
set -g window-status-current-fg black
set -g window-status-current-attr bold
set -g status-interval 60
set -g status-left-length 30
set -g status-left '#[fg=93](#S) #(whoami) '
set -g status-right '#[fg=93]#(cat /etc/hostname)'

bind -n M-C copy-mode
bind -n M-P paste-buffer
bind -t vi-copy v begin-selection
bind -t vi-copy V rectangle-toggle
bind -t vi-copy y copy-pipe "xclip"
setw -g mode-keys vi

