#!/bin/zsh

function fuzzy-git-branch
{
    local picked

    if git rev-parse --is-inside-work-tree >& /dev/null; then
        picked=$(
            (
                # git tag;
                # git branch --all --format='%(refname:lstrip=2)'
                git branch  --format='%(refname:lstrip=2)'
            ) | ${NOMAD_PICKER:-fzf}
        )

        LBUFFER="${LBUFFER}$picked"
    fi
}
zle -N fuzzy-git-branch


function fuzzy-file
{
    local file

    file=$(fd | fzf)
    LBUFFER="${LBUFFER}$file"
}
zle -N fuzzy-file
