otp_path: "/home/lsund/kerl/26.1.2"
apps_dirs:
  - "apps/*"
deps_dirs:
  - "_build/default/lib/*"
include_dirs:
  - "apps"
  - "apps/*/include"
  - "_build/default/lib"
  - "_build/default/lib/*/include"
diagnostics:
  enabled:
    - elvis
  disabled:
    - bound_var_in_pattern
exclude_unused_includes:
    - "etp/include/logger.hrl"
